# Generated by Django 3.0.8 on 2021-08-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='trash', max_length=250)),
                ('kind_of', models.CharField(choices=[('свалка', 'свалка'), ('помойка', 'помой-ка'), ('тот случай когда мусор это ты', 'тот случай когда мусор это ты')], default='trash', max_length=250)),
            ],
            options={
                'verbose_name': 'мусор',
                'verbose_name_plural': 'мусор',
            },
        ),
    ]
