# Generated by Django 3.0.8 on 2021-10-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='kind_of',
            field=models.CharField(choices=[('свалка', 'свалка'), ('помойка', 'помой-ка'), ('тот случай когда мусор это ты', 'тот случай когда мусор это ты')], max_length=250),
        ),
        migrations.AlterField(
            model_name='trash',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
