# Generated by Django 3.0.8 on 2021-10-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0002_auto_20211006_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='trash',
        ),
    ]
