# Generated by Django 3.0.8 on 2021-10-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyApp2', '0003_delete_trash'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('descp', models.TextField(blank=True, verbose_name='полное_описание')),
                ('image', models.ImageField(blank=True, upload_to='static\\media\\img')),
            ],
            options={
                'verbose_name': 'новости',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='some_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('descp', models.TextField(blank=True, verbose_name='полное_описание')),
                ('image', models.ImageField(blank=True, upload_to='static\\media\\img')),
            ],
            options={
                'verbose_name': 'предложение из вне',
                'verbose_name_plural': 'предложение из вне',
            },
        ),
    ]
