# Generated by Django 3.0.8 on 2021-11-06 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0004_news_some_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='some_new_fs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('descp', models.TextField(blank=True, verbose_name='полное_описание')),
                ('image', models.ImageField(blank=True, upload_to='static\\media\\img')),
                ('student_name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'предложение от учиника(цы)',
                'verbose_name_plural': 'предложение от учиника(цы)',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'verbose_name': 'ученик',
                'verbose_name_plural': 'ученики',
            },
        ),
    ]
