# Generated by Django 3.0.8 on 2022-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0005_some_new_fs_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='some_new',
            options={'verbose_name': 'предложение извне', 'verbose_name_plural': 'предложение извне'},
        ),
    ]
