# Generated by Django 3.0.8 on 2022-05-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0007_rast'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rast',
            options={'verbose_name': '_ученик_', 'verbose_name_plural': '_ученики_'},
        ),
    ]
