# Generated by Django 3.0.8 on 2022-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp2', '0008_auto_20220502_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='rast',
            name='image',
            field=models.ImageField(blank=True, upload_to='static\\media\\img'),
        ),
    ]
