# Generated by Django 3.0.8 on 2021-06-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
