# Generated by Django 3.0.8 on 2021-06-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyApp1', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_place', models.CharField(default='', max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('sum', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
        ),
    ]
