# Generated by Django 3.0.8 on 2021-06-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp1', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descp',
            field=models.TextField(blank=True, default='Text', verbose_name='полное_описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='event_place',
            field=models.CharField(default='place', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='place', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='place', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='sum',
            field=models.CharField(default='place', max_length=250),
        ),
    ]
